[package]
name = "cw-it"
version = "0.1.0"
authors = ["Pacman <pacman@apollo.farm>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = ["osmosis"]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []
# Support for Astroport
astroport = ["dep:cw20", "dep:astroport-types"]
osmosis = ["dep:osmosis-std", "dep:proptest", "dep:proptest-derive", "dep:liquidity-helper", "dep:cw-dex", "dep:apollo-cw-asset", "dep:cw-vault-standard", "dep:cw-vault-token", "dep:apollo-vault", "dep:cw-dex-router"]

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.6
"""

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
cosmwasm-std = {version = "1.2.1", features = ["stargate"]}
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
cosmwasm-schema = "1.2.1"
cosmrs = { version = "0.9.0", features = ["rpc", "cosmwasm"] }
testcontainers = { version = "0.14.0", features = ["experimental"] }
cosmos-sdk-proto = "0.15.0"
prost = { version = "0.11.2", default-features = false, features = [
    "prost-derive",
] }
config = { version = "0.13.2", features = ["yaml"] }
tokio = { version = "1.22.0", features = ["macros"] }
tonic = { version = "0.8.2", default-features = false }
git2 = "0.16.1"
git2_credentials = "0.10.0"
anyhow = "1.0.66"
serde_json = "1.0.89"
osmosis-test-tube = { git = "https://github.com/apollodao/test-tube.git", rev= "c55526a0c77bb38e4b6c97a4368f091304459a5a" }
# osmosis-test-tube = { path = "../test-tube/packages/osmosis-test-tube" }

# Astroport deps
astroport-types = { version = "0.1.3", optional = true }
cw20 = { version = "1.0.1", optional = true }

# Osmosis deps
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
osmosis-std = { version = "0.14.0", optional = true }
liquidity-helper = { version = "0.1.0", optional = true }
cw-dex = { version = "0.1.0", features = ["osmosis"], optional = true }
apollo-cw-asset = { version = "0.1.0", optional = true }
cw-vault-standard = { version = "0.2.0", features = ["lockup"], optional = true }
cw-vault-token = { version = "0.1.0", optional = true }
apollo-vault = { git = "https://github.com/apollodao/apollo-vault.git", features = ["lockup"], default-features = false, optional = true }
cw-dex-router = { version = "0.1.0", optional = true }

[dev-dependencies]
env_logger = "0.9.0"
