folder: "./tests/configs"
artifacts_folder: "./artifacts"
chain_config:
  name: "osmosis"
  chain_id: "localosmosis"
  prefix: "osmo"
  denom: "uosmo"
  gas_price: 1000000
  gas_adjustment: 1.2
  # https://github.com/confio/cosmos-hd-key-derivation-spec#the-cosmos-hub-path
  derivation_path: "m/44'/118'/0'/0/0"

  # leave this empty if using test_containers
  # rpc_endpoint: "http://localhost:26657"
  # grpc_endpoint: "http://localhost:9090"
  rpc_endpoint: ""
  grpc_endpoint: ""
container:
  name: "apollosturdy/localosmosis"
  tag: "v13.0.0-rc4"
  entrypoint: "/osmosis/setup.sh"
  volumes: [["tests/configs/osmosis/setup.sh", "/osmosis/setup.sh"]]
  ports: [26657, 1317, 9090, 9091]
# contracts list to download
# Do not repeat names
contracts:
  osmosis_liquidity_helper:
    url: "https://github.com/apollodao/osmosis_liquidity_helper.git"
    branch: "master"
    cargo_path: ""
    artifacts:
      - osmosis_liquidity_helper.wasm
