folder: "./tests/configs"
artifacts_folder: "./artifacts"
chain_config:
  name: "terra"
  chain_id: "localterra"
  prefix: "terra"
  denom: "uluna"
  gas_price: 1000000
  gas_adjustment: 1.2
  # https://github.com/confio/cosmos-hd-key-derivation-spec#the-cosmos-hub-path
  derivation_path: "m/44'/330'/0'/0/0"
  # leave this empty if using test_containers
  rpc_endpoint: ""
  grpc_endpoint: ""

container:
  name: "terramoney/localterra-core"
  tag: "2.0.1"
  entrypoint: "/entrypoint.sh"
  volumes:
    [
      ["tests/configs/terra/config", "/root/.terra/config"],
      ["tests/configs/terra/entrypoint.sh", "/entrypoint.sh"],
    ]
  ports: [26657, 1317, 9090, 9091]

# Chain to download contracts from
contract_chain_download_rpc: "https://terra-rpc.polkachu.com"

# contracts list to download
# Do not repeat names
contracts:
  # astroport_liquidity_helper:
  # url: "https://github.com/apollodao/astroport-liquidity-helper.git"
  # branch: "master"
  # cargo_path: ""
  # artifact: "astroport_liquidity_helper_unoptimized.wasm"
  # # Where to prefer getting contract, can be either "chain" or "url".
  # preferred_source: "url"
  # always_fetch: true # Whether to fetch even if contract exists in `artifacts folder`
  # chain_address: ""

  astro_token:
    url: "https://github.com/astroport-fi/astroport-core.git"
    branch: "c216ecd4f350113316be44d06a95569f451ac681"
    cargo_path: ""
    artifact: "astro_token.wasm"
    # Where to prefer getting contract, can be either "chain" or "url".
    preferred_source: "chain"
    always_fetch: true # Whether to fetch even if contract exists in `artifacts folder`
    chain_address: "terra1nsuqsk6kh58ulczatwev87ttq2z6r3pusulg9r24mfj2fvtzd4uq3exn26"

  # cw20_base:
  #   url: "https://github.com/CosmWasm/cw-plus/releases/download/v0.15.1/cw20_base.wasm"
  #   branch: ""
  #   cargo_path: ""
  #   artifacts:
  #     - cw20_base.wasm
  # cw3_fixed_multisig:
  #   url: "https://github.com/CosmWasm/cw-plus/releases/download/v0.15.1/cw3_fixed_multisig.wasm"
  #   branch: ""
  #   cargo_path: ""
  #   artifacts:
  #     - cw3_fixed_multisig.wasm
  # cw1_whitelist:
  #   url: "https://github.com/CosmWasm/cw-plus/releases/download/v0.15.1/cw1_whitelist.wasm"
  #   branch: ""
  #   cargo_path: ""
  #   artifacts:
  #     - cw1_whitelist.wasm
  # apollo_safe:
  #   url: "https://github.com/apollodao/apollo-safe-contracts.git"
  #   branch: "master"
  #   cargo_path: ""
  #   artifacts:
  #     - apollo_pay.wasm
  #     - apollo_safe_factory.wasm
  # steak_contracts:
  #   url: "https://github.com/apollodao/steak-contracts.git"
  #   branch: "dev/vault-token-abstraction"
  #   cargo_path: ""
  #   artifacts:
  #     - cw20_steak_hub.wasm
  #     - osmosis_steak_hub.wasm
  # astroport_vault:
  #   url: "https://github.com/apollodao/apollo-vaults.git"
  #   branch: "develop"
  #   cargo_path: "contracts/astroport-vault"
  #   artifacts:
  #     - astroport_vault.wasm
  # junoswap_vault:
  #   url: "https://github.com/apollodao/apollo-vaults.git"
  #   branch: "develop"
  #   cargo_path: "contracts/junoswap-vault"
  #   artifacts:
  #     - junoswap_vault.wasm
  # osmosis_vault:
  #   url: "https://github.com/apollodao/apollo-vaults.git"
  #   branch: "develop"
  #   cargo_path: "contracts/osmosis-vault"
  #   artifacts:
  #     - osmosis_vault.wasm

  # # NOTE: LEAVING ARTIFACTS EMPTY, IT WILL NOT COMPILE BUT DOWNLOAD THE REPO. THIS IS WANTED.
  # cw_token:
  #   url: "https://github.com/apollodao/cw-token.git"
  #   branch: "master"
  #   cargo_path: ""
  #   artifacts: []
  # cw_asset:
  #   url: "https://github.com/apollodao/cw-asset.git"
  #   branch: "main"
  #   cargo_path: ""
  #   artifacts: []
  # address_book:
  #   url: "../../contracts/address-book"
  #   branch: "master"
  #   cargo_path: ""
  #   artifacts:
  #     - address_book.wasm
